#!/bin/sh

sxhkd &

xinput set-prop 11 'libinput Disable While Typing Enabled' 1
xinput set-prop 11 "libinput Natural Scrolling Enabled" 1
xinput set-prop 11 "libinput Tapping Enabled" 1
xmodmap .config/keyboard/mythinkpad.xmodmap

feh --bg-scale pics/bg.jpg

picom --config .config/picom.conf &

bspc monitor -d '● ○ ○ ○ ○ ○' '○ ● ○ ○ ○ ○' '○ ○ ● ○ ○ ○' '○ ○ ○ ● ○ ○' '○ ○ ○ ○ ● ○' '○ ○ ○ ○ ○ ●'
bspc config split_ratio          .58

bspc config border_width         3
bspc config window_gap 8

# bspc config normal_border_color "#13141d"
# bspc config active_border_color "#ffffff"
bspc config focused_border_color "#ffffff"

bspc config single_monocle true
bspc config borderless_monocle true

tint2 &
dunst &

